version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-hamro
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: hamro-shiksha
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: